### ISSUE TITLE
Godot 4.5 IOS export fails to build in Xcode 16.3 due to undefined symbol errors

### ISSUE THREAD

**Issue by pananag** [AppLovin/AppLovin-MAX-Godot#61]
### MAX Plugin Version

1.2.0

### Godot Version

4.5

### Device/Platform Info

iOS

### Current Behavior

I export my game (which implements the applovin max plugin) to iOS using Godot 4.5.

I create and install the pod file and open the xcframework file (I'm basically doing the exactly same steps I used to do with Godot 4.4 and it was working)

I try to build and run to my iPhone device but build fails giving the following undefined symbol errors:

Undefined symbols for architecture arm64:
  "StringName::assign_static_unique_class_name(StringName*, char const*)", referenced from:
      AppLovinMAXGodotPlugin::_get_class_namev() const in libAppLovinMAXGodotPlugin.a[6](AppLovinMAXGodotPlugin.o)
  "Memory::alloc_static(unsigned long, bool)", referenced from:
      DefaultAllocator::alloc(unsigned long) in libAppLovinMAXGodotPlugin.a[6](AppLovinMAXGodotPlugin.o)
  "ClassDB::_add_class2(StringName const&, StringName const&)", referenced from:
      void ClassDB::_add_class<AppLovinMAXGodotPlugin>() in libAppLovinMAXGodotPlugin.a[6](AppLovinMAXGodotPlugin.o)
  "CharString::get_data() const", referenced from:
      +[NSObject(AppLovinMAXGodotPlugin) alg_objectFromGodotObject:] in libAppLovinMAXGodotPlugin.a[3](NSObject+AppLovinMAXGodotPlugin.o)
      +[NSObject(AppLovinMAXGodotPlugin) alg_objectFromGodotObject:] in libAppLovinMAXGodotPlugin.a[3](NSObject+AppLovinMAXGodotPlugin.o)
      +[NSString(AppLovinMAXGodotPlugin) alg_stringWithGodotString:] in libAppLovinMAXGodotPlugin.a[4](NSString+AppLovinMAXGodotPlugin.o)
  "String::utf8() const", referenced from:
      +[NSObject(AppLovinMAXGodotPlugin) alg_objectFromGodotObject:] in libAppLovinMAXGodotPlugin.a[3](NSObject+AppLovinMAXGodotPlugin.o)
      +[NSObject(AppLovinMAXGodotPlugin) alg_objectFromGodotObject:] in libAppLovinMAXGodotPlugin.a[3](NSObject+AppLovinMAXGodotPlugin.o)
      +[NSString(AppLovinMAXGodotPlugin) alg_stringWithGodotString:] in libAppLovinMAXGodotPlugin.a[4](NSString+AppLovinMAXGodotPlugin.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

I also get the same errors when I try to archive the project for uploading to app store.

If I remove the applovin-max-godot plugin from the godot export, the build completes without errors.

### Expected Behavior

I'd expect the build to complete and the game to run in my device.

### How to Reproduce

Export a Godot 4.5 project that implements the Applovin-Max-Godot v1.2.0 plugin to iOS.

Create a podfile for the project and install it. 

Open the xcworkspace file that is created after the podfile installation. Make sure that signing is setup.

Select a physical iOS device from the list of devices (no simulator) and try to build

Alternatively, try to archive the project. The build also fails.

 

### Reproducible in the demo app?

Not Tested

**Comment by ESnider** [comment]
I haven't tried the current plugin with Godot 4.5 but I had a lot of problems with it with Godot 4.4.1. I think you need to build the plugin yourself with the exact Godot iOS headers for it work correctly. I built the plugin myself and all the weird errors went away and it works okay now.

**Comment by pananag** [comment]
> I haven't tried the current plugin with Godot 4.5 but I had a lot of problems with it with Godot 4.4.1. I think you need to build the plugin yourself with the exact Godot iOS headers for it work correctly. I built the plugin myself and all the weird errors went away and it works okay now.

I tried to build with godot 4.5 headers, as described in the github readme,  but it failed. Should I build with 4.4.1 godot headers? But then will the project export correctly from Godot 4.5? As far as I understand the problem is changes in Godot 4.5 API which render the plugin incompatible.

**Comment by ESnider** [comment]
You could try building it with the 4.4.1 headers but really the whole thing about building the plugin yourself is so that it will have the right iOS Godot headers (or Android Godot headers I assume). I'm not so up on GitHub etiquette, like is it okay to talk about whatever we want here or are we supposed to focus on the bug only? I dunno. :) But maybe we can talk about what went wrong when you tried to build it with the 4.5 headers here.

**Comment by pananag** [comment]
@ESnider 

When I try to build with 4.5 headers, when I execute python3 godot_plugin.py build_ios  I get the following errors:


/Users/gameaki/AppLovin-MAX-Godot/godot/core/object/object.h:33:10: fatal error: 
      'core/disabled_classes.gen.h' file not found
   33 | #include "core/disabled_classes.gen.h"


The following build commands failed:
	CompileC /Users/gameaki/Library/Developer/Xcode/DerivedData/AppLovin-MAX-Godot-dmlwgmhsprhhpebnshchxiqlwnhh/Build/Intermediates.noindex/ArchiveIntermediates/AppLovin-MAX-Godot-Plugin/IntermediateBuildFilesPath/AppLovin-MAX-Godot-Plugin.build/Release-iphoneos/AppLovinMAXGodotPlugin.build/Objects-normal/arm64/NSString+AppLovinMAXGodotPlugin.o /Users/gameaki/AppLovin-MAX-Godot/Source/iOS/AppLovin-MAX-Godot-Plugin/Categories/NSString+AppLovinMAXGodotPlugin.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'AppLovinMAXGodotPlugin' from project 'AppLovin-MAX-Godot-Plugin')
	Archiving workspace AppLovin-MAX-Godot with scheme AppLovin-MAX-Godot-Plugin
(2 failures)
Error during iOS plugin build: An error occurred while generating the xcframework: Command '['xcodebuild', 'archive', '-workspace', 'AppLovin-MAX-Godot.xcworkspace', '-scheme', 'AppLovin-MAX-Godot-Plugin', '-archivePath', './Source/iOS/build/archive/ios_release.xcarchive', '-sdk', 'iphoneos', 'SKIP_INSTALL=NO', 'GCC_PREPROCESSOR_DEFINITIONS=']' returned non-zero exit status 65.

**Comment by pananag** [comment]
@ESnider 

I managed to build with 4.5 headers. The problem was with scons path which is needed for generating the godot engine's iOS headers when preparing the working space for ios development. 

I replaced the existing godot project's ios plugin with the generated one with 4.5 headers and now the build in xcode completes  successfully.

**Comment by mrussogit** [comment]
Hi @pananag , I tried following @ESnider guide to update the headers. I' m still getting errors like 

AppLovinMAXGodotPlugin not found, make sure you marked all 'AppLovinMAX' plugins on export tab

The plugin is ticked on Project Settings / Plugins and also in resources tab. I followed up to the point I rebuilt the plugin based on godot4.5-stable and replaced the libAppLovinMAXGodotPlugin.a to my game project. What am I doing wrong?

**Comment by pananag** [comment]
@mrussogit  You also need to tick the Applovin plugin also in the export tab of the platform you are exporting to. There is an option for what plugins should be included when exporting.

**Comment by mrussogit** [comment]
> [@mrussogit](https://github.com/mrussogit) You also need to tick the Applovin plugin also in the export tab of the platform you are exporting to. There is an option for what plugins should be included when exporting.

Thanks for the response, yes the plugin is ticked on Project Settings/Plugins. It has to be ticked on Project Settings/Plugins and also checked on Export Resources otherwise the plugin won't be packed in too. This is why it is puzzling after all the hassle and time to recompile the plugin, stuck in this dead end. I was checking AppLovin git hub, even the Defold plugin is more recently updated than Godot :(

**Comment by pananag** [comment]
@mrussogit Unfortunately, I can't help you more because AppLovin banned my account without any notice or warning. I just had an ad unit that showed a few ads every day and they banned us...

I installed this addon: https://github.com/godot-sdk-integrations/godot-admob which implements mediation. It is also part of the official godot 3rd party sdk integration program which aims to keep the integrations maintained. 

So far, it works like a charm and has a very easy implementation. I highly recommend it for ads service with mediation support, unless you don't want admob to be the main ads provider.

**Comment by mrussogit** [comment]
thanks for the heads up! I'd prefer AppLovin to be the main provider for games in Godot. We already have a few games in Unity using both and AppLovin and Admob and AppLovin seems to generate more revenue. Sorry your account was banned. :(

**Comment by ESnider** [comment]
I've moved on to AdMob mediation and have stopped using AppLovin in my most recent game. The lack of easy integration in Godot combined with how the playable ads were so upsetting and confusing to my players convinced me to switch even though the AdMob plugin is made by a third party.
